(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.doesntmatter = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var makeWrapper = require("wrap.js")

var meta = JSON.parse("{\"filename\":\"./contato/index.html\",\"pathname\":\"/contato/\",\"title\":\"contato\",\"date\":\"2017-06-23T19:16:14.652Z\",\"summary\":\"Seu e-mail:  \\nSua mensagem:  \\n Enviar\"}")
var content = require("/tmp/react-site/levypla/contato/content.js")

module.exports = makeWrapper(meta, content)
module.exports.meta = meta

},{"/tmp/react-site/levypla/contato/content.js":2,"wrap.js":undefined}],2:[function(require,module,exports){
module.exports = "<h1>Deixe uma mensagem e seja sumariamente ignorado:</h1>\n<form action=https://formspree.io/egmlevy@gmail.com method=post>\n  <div class=\"field is-horizontal\">\n    <div class=\"field-label is-normal\">\n      <label class=\"label\">Seu e-mail:</label>\n    </div>\n    <div class=\"field-body\">\n      <div class=\"field\">\n        <p class=\"control\">\n          <input class=\"input\" type=\"email\" name=\"email\">\n        </p>\n      </div>\n    </div>\n  </div>\n  <div class=\"field is-horizontal\">\n    <div class=\"field-label is-normal\">\n      <label class=\"label\">Sua mensagem:</label>\n    </div>\n    <div class=\"field-body\">\n      <div class=\"field\">\n        <p class=\"control\">\n          <textarea class=\"textarea\" name=\"mensagem\"></textarea>\n        </p>\n      </div>\n    </div>\n  </div>\n  <div class=\"field is-horizontal\">\n    <div class=\"field-label\">\n      <!-- left blank for alignment -->\n    </div>\n    <div class=\"field-body\">\n      <div class=\"field\">\n        <p class=\"control\">\n          <button type=\"submit\" class=\"button is-medium\">Enviar</button>\n        </p>\n      </div>\n    </div>\n  </div>\n</form>\n"
},{}]},{},[1])(1)
});